### ISSUE TITLE
IE Microsoft Edge rotation

### ISSUE THREAD

**Issue by Thann1** [boxslider/slider#28]
Hi, there is an issue with Vertical 3D Scroll at Microsoft Edge IE, that shows strange behavior on the 4th animation, somehow rotating in the wrong direction. Could you please give a hint how it can be solved?
Thanks.
Best regards
Dina

**Comment by p-m-p** [comment]
Firefox also had this issue, I've not done much with this plugin in a while but may look into a revamp soon.
